apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-webapp
  template:
    metadata:
      labels:
        app: tomcat-webapp
    spec:
      containers:
      - name: tomcat
        image: itsbijaya/tomcat-webapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-webapp-service
spec:
  selector:
    app: tomcat-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
